### ISSUE TITLE
Recent issues installing on OS X and Python 3.5.1

### ISSUE THREAD

**Issue by nikolay** [msabramo/requests-unixsocket#19]
```
$ pip install -U requests-unixsocket
Collecting requests-unixsocket
  Downloading requests-unixsocket-0.1.5.tar.gz
    Complete output from command python setup.py egg_info:
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "/Users/user/Projects/project/.env/versions/3.5.1/envs/myenv/lib/python3.5/site-packages/pbr/core.py", line 111, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "/Users/user/Projects/project/.env/versions/3.5.1/envs/myenv/lib/python3.5/site-packages/pbr/util.py", line 264, in cfg_to_args
        wrap_commands(kwargs)
      File "/Users/user/Projects/project/.env/versions/3.5.1/envs/myenv/lib/python3.5/site-packages/pbr/util.py", line 566, in wrap_commands
        cmdclass = ep.resolve()
      File "/Users/user/Projects/project/.env/versions/3.5.1/envs/myenv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
    ImportError: No module named 'monolithic'
    error in setup command: Error parsing /private/var/folders/cb/cxxqz_g94jd1x5tjwrklxgd00000gn/T/pip-build-r8bqv_7b/requests-unixsocket/setup.cfg: ImportError: No module named 'monolithic'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/cb/cxxqz_g94jd1x5tjwrklxgd00000gn/T/pip-build-r8bqv_7b/requests-unixsocket/
```

**Comment by msabramo** [comment]
Hmmm, that is weird. This project doesn't use anything called `monolithic`:

```
$ ag monolithic
<nothing>
```

```
$ pip download requests-unixsocket==0.1.5
Collecting requests-unixsocket==0.1.5
  Using cached requests-unixsocket-0.1.5.tar.gz
  Saved ./requests-unixsocket-0.1.5.tar.gz
Collecting requests>=1.1 (from requests-unixsocket==0.1.5)
  Using cached requests-2.10.0-py2.py3-none-any.whl
  Saved ./requests-2.10.0-py2.py3-none-any.whl
Collecting urllib3>=1.8 (from requests-unixsocket==0.1.5)
  Using cached urllib3-1.16-py2.py3-none-any.whl
  Saved ./urllib3-1.16-py2.py3-none-any.whl
Successfully downloaded requests-unixsocket requests urllib3

$ tar xvf requests-unixsocket-0.1.5.tar.gz
x requests-unixsocket-0.1.5/
x requests-unixsocket-0.1.5/.travis.yml
x requests-unixsocket-0.1.5/AUTHORS
x requests-unixsocket-0.1.5/ChangeLog
x requests-unixsocket-0.1.5/LICENSE
x requests-unixsocket-0.1.5/PKG-INFO
x requests-unixsocket-0.1.5/pytest.ini
x requests-unixsocket-0.1.5/README.rst
x requests-unixsocket-0.1.5/requests_unixsocket/
x requests-unixsocket-0.1.5/requests_unixsocket/__init__.py
x requests-unixsocket-0.1.5/requests_unixsocket/adapters.py
x requests-unixsocket-0.1.5/requests_unixsocket/tests/
x requests-unixsocket-0.1.5/requests_unixsocket/tests/test_requests_unixsocket.py
x requests-unixsocket-0.1.5/requests_unixsocket/testutils.py
x requests-unixsocket-0.1.5/requests_unixsocket.egg-info/
x requests-unixsocket-0.1.5/requests_unixsocket.egg-info/dependency_links.txt
x requests-unixsocket-0.1.5/requests_unixsocket.egg-info/not-zip-safe
x requests-unixsocket-0.1.5/requests_unixsocket.egg-info/pbr.json
x requests-unixsocket-0.1.5/requests_unixsocket.egg-info/PKG-INFO
x requests-unixsocket-0.1.5/requests_unixsocket.egg-info/requires.txt
x requests-unixsocket-0.1.5/requests_unixsocket.egg-info/SOURCES.txt
x requests-unixsocket-0.1.5/requests_unixsocket.egg-info/top_level.txt
x requests-unixsocket-0.1.5/requirements.txt
x requests-unixsocket-0.1.5/setup.cfg
x requests-unixsocket-0.1.5/setup.py
x requests-unixsocket-0.1.5/test-requirements.txt
x requests-unixsocket-0.1.5/tox.ini

$ ag monolithic requests-unixsocket-0.1.5/setup.cfg
<nothing>
```

I wonder if it's an issue with [pbr](https://pypi.python.org/pypi/pbr)?

**Comment by msabramo** [comment]
If you can show me a way to reproduce this issue, I'll reopen it.

Thanks!
